### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/discoverdotnet#44]
A reddit user noted that the site doesn't work in IE, and they're not wrong. I took a quick look to see if it was easily fixable and got part way there. However, there are still some layout issues with the footer not being pushed down (possibly due to `flex: 1` usage) and cards not rendering.

At this point I've spent all the time I can on this unless there's a large outcry for IE support. Otherwise, I welcome someone from the community who's much better with the front-end and JavaScript to take a look.

**Comment by JuergenGutsch** [comment]
Hey @daveaglick,
I could have a look :-)

**Comment by daveaglick** [comment]
Awesome! It bugs me that the site isn't working great on IE, but I just don't have the time to look closely at it.

**Comment by JuergenGutsch** [comment]
Where is the repository for the website to create PRs?

Just found another CSS issue with the header logo. It's too small and kinda stretched in IE.
To fix this, change this width to auto and the max-height to min-height:
~~~ css
@media (min-width: 768px) {
.logo-header .logo img {
    width: auto;
}}

.logo-header .logo img {
    width: 100%;
    min-height: 50%;
    -webkit-filter: drop-shadow(0 0 1rem indigo);
    filter: drop-shadow(0 0 1rem indigo);
}
~~~

**Comment by JuergenGutsch** [comment]
Because of the footer:
* Remove height:100% from html and body tag, because the makes the elements as height as the view port in IE, instead of as height as the document.
* Remove flex:1 from the main tag (IE11: "Partial support is due to large amount of bugs present (see known issues)" https://caniuse.com/#search=flex)

**Comment by JuergenGutsch** [comment]
The cards are not displayed because of a JavaScript error that happens in IE only. Still need to figure out what happened exactly:
~~~
ReferenceError: "anyResults" ist undefiniert
   {
      [functions]: ,
      __proto__: { },
      description: ""anyResults" ist undefiniert",
      message: ""anyResults" ist undefiniert",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: "anyResults" ist undefiniert
   at Function code (Function code:1:12)
   at fn.prototype._render (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:32683)
   at Anonymous function (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:63771)
   at St.prototype.get (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:15991)
   at St (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:15890)
   at hn.prototype.$mount (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:63639)
   at hn.prototype.$mount (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:86321)
   at Yt.init (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:22245)
   at Anonymous function (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:52303)
   at b (https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js:6:52168)"
   }
~~~

**Comment by JuergenGutsch** [comment]
Will do a PR soon
